### PR TITLE
Upgrade to SpiderMonkey 67

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/mozjs/186)

### CODE REVIEW

**Comment by jdm** [comment]
Windows build doesn't find a viable llvm-config.

**Comment by asajeffrey** [comment]
Oh joy... https://travis-ci.com/servo/mozjs/jobs/208965905#L2085
```
ERROR: Python 3.5 or newer is required to build. Ensure a `python3.x` executable is in your PATH or define PYTHON3 to point to a Python 3.5 executable.
```

**Comment by asajeffrey** [comment]
Apart from the travis failure, this all looks sensible. We should edit the git history to make the version bump the last commit.

**Comment by jdm** [comment]
The travis failure will be fixed by https://github.com/servo/mozjs/pull/188.

**Comment by jdm** [comment]
I'm retrying the failed jobs individually.

**Pull request merged**
