### PR TITLE
Move to travis for homu.

### PR DESCRIPTION
**Pull request by Ms2ger**
[Review on Reviewable](https://reviewable.io/reviews/servo/mozjs/58)

### CODE REVIEW

**Comment by metajack** [comment]
@bors-servo r+

Are you going to submit a PR to saltfs as well?


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/mozjs/58)

**Comment by edunham** [comment]
:+1:

**Pull request merged**
