### PR TITLE
Version bump for crates.io

### PR DESCRIPTION
**Pull request by fitzgen**
r? @asajeffrey

---
This change is [Reviewable](https://reviewable.io/reviews/servo/mozjs/127)

### CODE REVIEW

**Comment by asajeffrey** [comment]
I thought we were planning on using the SM version as the `x` in `0.x.y`?

**Comment by fitzgen** [comment]
Yeah, once we actually have SMs that we know what version they came from. This was just the minimal thing we can publish given what's already on crates.io.

**Comment by fitzgen** [comment]
I guess the current SM is 50 here, I can make this 0.50.0

**Comment by fitzgen** [comment]
Ok, this is 0.50.0

**Comment by fitzgen** [comment]
```
$ cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging mozjs_sys v0.50.0 (file:///home/fitzgen/mozjs)
   Verifying mozjs_sys v0.50.0 (file:///home/fitzgen/mozjs)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.33
   Compiling mozjs_sys v0.50.0 (file:///home/fitzgen/mozjs/target/package/mozjs_sys-0.50.0)
   Compiling cc v1.0.3
   Compiling libz-sys v1.0.18
    Finished dev [unoptimized + debuginfo] target(s) in 57.98 secs
   Uploading mozjs_sys v0.50.0 (file:///home/fitzgen/mozjs)
error: api errors: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

cc @SimonSapin ^

**Comment by SimonSapin** [comment]
@fitzgen I think crates.io recently started to require you to accept being added. Is something visible on https://crates.io/dashboard?

**Comment by fitzgen** [comment]
Huh. I don't see anything there, or in my inbox.

**Comment by fitzgen** [comment]
Aha! https://crates.io/me/pending-invites

**Comment by fitzgen** [comment]
Thanks @SimonSapin !

**Comment by KiChjang** [comment]
Well, would you take a look at this...
```
LC02NP4XNG3QC:mozjs keithyeung$ rustup run nightly cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Packaging mozjs_sys v0.50.0 (file:///Users/keithyeung/Workspace/mozjs)
   Verifying mozjs_sys v0.50.0 (file:///Users/keithyeung/Workspace/mozjs)
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling mozjs_sys v0.50.0 (file:///Users/keithyeung/Workspace/mozjs/target/package/mozjs_sys-0.50.0)
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.33
   Compiling cc v1.0.3
   Compiling libz-sys v1.0.18
    Finished dev [unoptimized + debuginfo] target(s) in 153.39 secs
   Uploading mozjs_sys v0.50.0 (file:///Users/keithyeung/Workspace/mozjs)
error: api errors: max upload size is: 10485760
```

**Comment by SimonSapin** [comment]
Are there files in the repo like tests that aren’t used for `cargo build` and that we could exclude from crates.io tarballs?

**Comment by SimonSapin** [comment]
Is ICU optional? Does Servo enable it?

```
40M	mozjs/js/src/tests
35M	mozjs/js/src/jit-test
11M	mozjs/js/src/octane
55M	mozjs/intl/icu
10M	mozjs/config/external/icu

**Comment by fitzgen** [comment]
I'm working on adding `excludes` to `Cargo.toml`.

ICU is optional to build, but necessary for some web/js APIs as I understand it.

We can bump the crates.io size limit in special cases, after investigating what we can do to slim the package down.

**Comment by SimonSapin** [comment]
Perhaps ICU could be a separate crate?

**Comment by fitzgen** [comment]
Perhaps. I'm unsure if the vendored m-c ICU has any patches or not, and whether SM will build with a system/non-vendored ICU.

**Comment by asajeffrey** [comment]
Oh rats. Nearly there!

**Pull request merged**
