### PR TITLE
dependencies: Update bindgen

### PR DESCRIPTION
**Pull request by mrobinson**

### CODE REVIEW

**Comment by sagudev** [comment]
This update still does not include float16 fix unfortunately.

**Review by sagudev — APPROVED** [review]

**Comment by mrobinson** [comment]
It looks like 0.69.2 includes the fix based on the diff:

https://github.com/rust-lang/rust-bindgen/compare/v0.69.2...main

**Comment by sagudev** [comment]
> It looks like 0.69.2 includes the fix based on the diff:
> 
> [rust-lang/rust-bindgen@v0.69.2...main](https://github.com/rust-lang/rust-bindgen/compare/v0.69.2...main)

I think you need to compare between tags: https://github.com/rust-lang/rust-bindgen/compare/v0.69.1...v0.69.2

Comparing tag from main just shows what is on main but not in tag I think.

**Comment by mrobinson** [comment]
Huh. Either way, as long as the released version is 0.69.3, this should be useful.

**Pull request merged**
