### PR TITLE
Add AArch64 as an architecture supported by Double-Conversion.

### PR DESCRIPTION
**Pull request by akiss77**
Tested for correctness as described in the comment.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Would it work to use <https://mxr.mozilla.org/mozilla-central/source/mfbt/double-conversion/fix-aarch64-macro.patch> instead?

**Comment by akiss77** [comment]
If I see it right, the patch would not apply per se, but the idea (using the macro __AARCH64EL__) can be used. However, I'm not sure why support is limited for little endian variants only. (I do have to admint that my box is little endian as well and have no access to a big endian variant, and have no deep knowledge of the code base either -- but after a quick look at the code, I see nothing against EB...)

**Comment by akiss77** [comment]
So, the question is: shall I try to adapt the above-referenced patch (which is mostly replacing `__aarch64__` with `__AARCH64EL__` only)?

**Comment by jdm** [comment]
Yes, I think I would prefer adapting that patch.

**Comment by akiss77** [comment]
What do you think about the adapted patch?

**Pull request merged**
