### PR TITLE
testing travis

### PR DESCRIPTION
**Pull request by jdm**
[Review on Reviewable](https://reviewable.io/reviews/servo/mozjs/53)

### CODE REVIEW

**Comment by Ms2ger** [comment]
@Manishearth can you please turn off appveyor?

@jdm travis passed

**Comment by jdm** [comment]
I suppose the real test here is to make a change that should break the build and ensure that happens :)

**Comment by larsbergstrom** [comment]
@jdm @Ms2ger Is this ready to be merged, once you remove the "Break stuff" commit?

**Comment by jdm** [comment]
Closing in favour of #57.

**Pull request closed without merging**
