### PR TITLE
Update Spidermonkey to 86

### PR DESCRIPTION
**Pull request by sagudev**
Still having problems with macOS.

### CODE REVIEW

**Comment by sagudev** [comment]
I do not have macOS machine for debugging.
```
Assertion failure: gInitialized (calling TimeDuration too early), at /Users/runner/work/mozjs/mozjs/mozjs/mozglue/misc/TimeStamp_darwin.cpp:97
```
@jdm any idea?

**Comment by sagudev** [comment]
lldb gives:
```
lldb /Users/runner/work/mozjs/mozjs/target/debug/deps/mozjs_sys-13817ad2d84d6e57
(lldb) target create "/Users/runner/work/mozjs/mozjs/target/debug/deps/mozjs_sys-13817ad2d84d6e57"
Current executable set to '/Users/runner/work/mozjs/mozjs/target/debug/deps/mozjs_sys-13817ad2d84d6e57' (x86_64).
(lldb) bt
error: invalid process
(lldb) run
Process 7251 launched: '/Users/runner/work/mozjs/mozjs/target/debug/deps/mozjs_sys-13817ad2d84d6e57' (x86_64)
Assertion failure: gInitialized (calling TimeDuration too early), at /Users/runner/work/mozjs/mozjs/mozjs/mozglue/misc/TimeStamp_darwin.cpp:97
Process 7251 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001011c10be mozjs_sys-13817ad2d84d6e57`mozilla::BaseTimeDurationPlatformUtils::TicksFromMilliseconds(aMilliseconds=2000) at TimeStamp_darwin.cpp:97:3
   94
   95   int64_t BaseTimeDurationPlatformUtils::TicksFromMilliseconds(
   96       double aMilliseconds) {
-> 97     MOZ_ASSERT(gInitialized, "calling TimeDuration too early");
   98     double result = (aMilliseconds * kNsPerMsd) / sNsPerTick;
   99     if (result > double(INT64_MAX)) {
   100      return INT64_MAX;
Target 0: (mozjs_sys-13817ad2d84d6e57) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001011c10be mozjs_sys-13817ad2d84d6e57`mozilla::BaseTimeDurationPlatformUtils::TicksFromMilliseconds(aMilliseconds=2000) at TimeStamp_darwin.cpp:97:3
    frame #1: 0x0000000100152025 mozjs_sys-13817ad2d84d6e57`mozilla::BaseTimeDuration<mozilla::TimeDurationValueCalculator>::FromMilliseconds(aMilliseconds=2000) at TimeStamp.h:155:9
    frame #2: 0x00000001001177e2 mozjs_sys-13817ad2d84d6e57`mozilla::BaseTimeDuration<mozilla::TimeDurationValueCalculator>::FromSeconds(aSeconds=2) at TimeStamp.h:145:12
    frame #3: 0x00000001009a0991 mozjs_sys-13817ad2d84d6e57`::__cxx_global_var_init() at Nursery.cpp:991:45
    frame #4: 0x00000001009a09a9 mozjs_sys-13817ad2d84d6e57`_GLOBAL__sub_I_Unified_cpp_js_src_gc1.cpp at Unified_cpp_js_src_gc1.cpp:0
    frame #5: 0x000000010413b1d3 dyld`ImageLoaderMachO::doModInitFunctions(ImageLoader::LinkContext const&) + 535
    frame #6: 0x000000010413b5de dyld`ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 40
    frame #7: 0x0000000104135ffb dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 493
    frame #8: 0x00000001041340b4 dyld`ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
    frame #9: 0x0000000104134154 dyld`ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
    frame #10: 0x00000001041226a8 dyld`dyld::initializeMainExecutable() + 199
    frame #11: 0x0000000104127bba dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6667
    frame #12: 0x0000000104121227 dyld`dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
    frame #13: 0x0000000104121025 dyld`_dyld_start + 37
```

**Comment by jdm** [comment]
This looks like an ordering issue. That's supposed to be initialized by https://searchfox.org/mozilla-central/source/mozglue/misc/TimeStamp_darwin.cpp#138, which is invoked in https://searchfox.org/mozilla-central/source/mozglue/misc/TimeStamp.cpp#38, which should be called due to the static global https://searchfox.org/mozilla-central/source/mozglue/misc/TimeStamp.cpp#71

**Comment by sagudev** [comment]
At https://hg.mozilla.org/mozilla-central/rev/af56f51a55b1:

Don't use TimeDuration in static initializer. r=jandem
On Darwin this would cause a race between two static initializers.

**Comment by jdm** [comment]
Added a commit that makes the failure disappear on my local mac environment.

**Comment by sagudev** [comment]
@jdm Thanks. I tried using GitHub actions with tmate for debugging, but I didn't get very far (I mostly just revert some suspicious commits from Mozilla-central)

**Comment by sagudev** [comment]
@jdm Anything else needed to be done for merge?

**Comment by jdm** [comment]
@sagudev We prefer not to merge before the corresponding changes to Servo are ready and tested, otherwise we block any further changes to the crate until Servo is using them.

**Pull request merged**
