### PR TITLE
Added Traceable for PropertyDescriptor

### PR DESCRIPTION
**Pull request by Redfire75369**

### CODE REVIEW

**Comment by sagudev** [comment]
Relevant code in mozilla: https://searchfox.org/mozilla-central/source/js/src/gc/RootMarking.cpp#212

**Review by jdm — APPROVED** [review]

**Comment by Redfire75369** [comment]
The error on debug windows arm64 seems spurious? There's no error and seemingly a segfault in rustc?

**Comment by sagudev** [comment]
> The error on debug windows arm64 seems spurious? There's no error and seemingly a segfault in rustc? Could you perhaps try rerunning the check?

I also managed to get this on main: https://github.com/servo/mozjs/actions/runs/7068898831

**Comment by Redfire75369** [comment]
The most likely cause seems to be rust 1.74, although there's a chance its from the upgrade to VS 17.8.34316.

**Comment by sagudev** [comment]
I was diffing from [last know working build](https://github.com/servo/mozjs/actions/runs/7068047786/job/19242172720) and OS image and rust version is the same.

**Comment by Redfire75369** [comment]
Weird, the debug aarch64 windows build didn't fail this time

**Comment by Redfire75369** [comment]
In that case, this certainly seems spurious.

**Comment by sagudev** [comment]
50% of manually dispatched runs failed

**Comment by sagudev** [comment]
Or maybe it is rust problem after all: https://github.com/rust-lang/rust/issues/118462

**Pull request merged**
