### PR TITLE
Use octal notation for permission modes

### PR DESCRIPTION
**Pull request by eliasp**
As of Python 3, decimal notations of octal values for permission modes
are no longer permitted and will result in a `SyntaxError` exception
(`invalid token`).

Using the proper octal notation which is also Python 2.7 compatible will
fix this issue.

---
This change is [Reviewable](https://reviewable.io/reviews/servo/mozjs/87)

### CODE REVIEW

**Comment by eliasp** [comment]
The build failure is unrelated (a crates download failed).
The build should be retriggered.

**Comment by jdm** [comment]
All of this code is imported from upstream: http://hg.mozilla.org/mozilla-central/ . These changes will need to be submitted as patches in https://bugzilla.mozilla.org/, or they'll be overwritten next time we update this repository.

**Comment by Ms2ger** [comment]
@eliasp do you want to submit upstream or should I?

**Comment by eliasp** [comment]
@Ms2ger would be awesome if you could take care of this. Never worked in the Mozilla upstream ecosystem and would require quite a bit effort for me to get this done…
thanks a lot!

**Comment by Manishearth** [comment]
FWIW if you want to try, I'm willing to help mentor you through the process. Otherwise one of us can submit it for you, of course 😄

**Comment by Ms2ger** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1293234 for the parts that are definitely under Mozilla control; will poke around for the other parts.

**Comment by eliasp** [comment]
@Manishearth thanks a lot for the offer of mentoring me, but I'm already active in too many other projects. This was more or less just a drive-by PR as I wanted to build Servo on my box for playing with it ;)

**Comment by eliasp** [comment]
@Ms2ger thanks a lot for submitting it upstream.

**Pull request closed without merging**
