### PR TITLE
Backport of bug 1224722 - Enable executing multiple embedding-provided inputs as self-hosted JS during runtime startup

### PR DESCRIPTION
**Pull request by tschneidereit**
@michaelwu wanted to use this in his self-hosting experiments.

[Review on Reviewable](https://reviewable.io/reviews/servo/mozjs/65)

### CODE REVIEW

**Comment by Ms2ger** [comment]
We should just do a full update, except nobody seems to want to do that or explain how to do it.

**Comment by tschneidereit** [comment]
> We should just do a full update, except nobody seems to want to do that or explain how to do it.

I agree in principle. However, applying the hacks that make the current mozjs work for Servo on top of current mozilla-central is non-trivial, and won't ever get easier, really. Hence, I'd like to instead get rid of as many of these hacks as possible, partly by working around the need for them, partly by upstreaming proper fixes. I started looking into this a few weeks back, and it seems feasible. In fact, it's one of my Q4 goals to get to a point where we can use pristine upstream and do away with mozjs in its current form entirely. (Whether I can manage to actually get to that point this quarter remains to be seen. I *did* lose a few weeks because of that stupid accident.)

For the time being, backporting this patch took about 10 minutes, so seemed to be well-worth it.

**Comment by michaelwu** [comment]
I'm getting an assertion at MOZ_ASSERT(hasContexts()); in JSRuntime::evaluateSelfHosted. Should it be the opposite?

**Comment by michaelwu** [comment]
MOZ_ASSERT(selfHostingGlobal_); is also failing. Guess I'm probably doing something wrong..

**Comment by michaelwu** [comment]
Ok, seems to work.

**Pull request closed without merging**
