### PR TITLE
Bump up `config.{guess,sub}` to latest and fix the Android-on-ARM pattern in `configure` and in `android.m4

### PR DESCRIPTION
**Pull request by akiss77**
Versions of `config.{guess,sub}` from 2009 & 2011 are way too old, latest versions
recognize newer architectures as well, e.g., aarch64, so a bump-up is timely. However,
a pattern used in `configure` (originating from `android.m4`) is too restrictive:
 `arm-linux*-android*` does not match the `arm-unknown-linux-androideabi` string
returned by recent `config.sub`, so it needs fixing.

### CODE REVIEW

**Comment by jdm** [comment]
Please also submit a pull request to servo/servo that makes use of this too, so we avoid the problem we had last time and this gets tested immediately :)

**Comment by akiss77** [comment]
Is that really servo/servo (where I cannot find anything similar), or should it be https://mxr.mozilla.org/mozilla-central/source/build/autoconf/android.m4 ? (If the latter, I'll have to find out how to propose a patch there.)

**Comment by jdm** [comment]
What I mean is that the servo repository is locked to particular revisions of dependencies (like mozjs) via the Cargo.lock file. You can update these revisions using `./mach update-cargo -p mozjs-sys --precise <hash>` and make a PR for the changes.

**Comment by akiss77** [comment]
FYI: contributed the `android.m4` fix upstream ( https://bugzilla.mozilla.org/show_bug.cgi?id=1122111 )

**Comment by jdm** [comment]
Thanks!

**Pull request merged**
