### PR TITLE
Disable zealous GC in release builds.

### PR DESCRIPTION
**Pull request by asajeffrey**
[Review on Reviewable](https://reviewable.io/reviews/servo/mozjs/60)

### CODE REVIEW

**Comment by michaelwu** [comment]
It's not enabled. An additional env flag is required to turn it on.

**Comment by asajeffrey** [comment]
Running the Dromaeo JS tests with and without gczeal enabled at compile-time... Without gczeal: http://i.imgur.com/iXNJf9e.png. With gczeal: http://i.imgur.com/FP17NH3.png. Looks like about 5% difference in performance on tests which perform allocation.

**Comment by jdm** [comment]
Ok! A measurable difference is a valid reason to turn it off, I think.

**Comment by michaelwu** [comment]
@bors-servo: r-
(don't think it matters but I'll r- to be sure)

There are functions which are only built when GC zeal is enabled, but which are specified in the bindings. You'll have to remove the GC zeal functions in the bindings to make this work everywhere. Unfortunately, the platforms we actually test on normally don't show this problem, but it can break windows and android.

I agree with this change, btw. It was only due to linking that zeal needed to be enabled everywhere, but I don't think we need to set the zeal from code. Setting zeal via env vars should be enough.

**Comment by asajeffrey** [comment]
Hmm, that's annoying. We're living with a 5% slowdown because of issues on platforms we don't test against. We should at least open an issue for this and leave it open until we fix the bindings.

**Comment by michaelwu** [comment]
Fix the bindings and this can land. This affects Android, Windows, and CEF bindings. I think you just need to delete the gc zeal functions in all the jsapi_* files.

**Comment by asajeffrey** [comment]
OK, I'll have a look at the jsapi files later today.

**Comment by asajeffrey** [comment]
@michaelwu are you meaning:

$ grep -ir zeal rust-mozjs/
rust-mozjs/src/jsapi_linux_32.rs:    #[link_name = "_Z12JS_GetGCZealP9JSContextPhPjS2_"]
rust-mozjs/src/jsapi_linux_32.rs:    pub fn JS_GetGCZeal(cx: *mut JSContext, zeal: *mut u8,
rust-mozjs/src/jsapi_linux_32.rs:    #[link_name = "_Z12JS_SetGCZealP9JSContexthj"]
rust-mozjs/src/jsapi_linux_32.rs:    pub fn JS_SetGCZeal(cx: *mut JSContext, zeal: u8, frequency: u32);
rust-mozjs/src/jsapi_macos_64.rs:    #[link_name = "_Z12JS_GetGCZealP9JSContextPhPjS2_"]
rust-mozjs/src/jsapi_macos_64.rs:    pub fn JS_GetGCZeal(cx: *mut JSContext, zeal: *mut u8,
rust-mozjs/src/jsapi_macos_64.rs:    #[link_name = "_Z12JS_SetGCZealP9JSContexthj"]
rust-mozjs/src/jsapi_macos_64.rs:    pub fn JS_SetGCZeal(cx: *mut JSContext, zeal: u8, frequency: u32);
rust-mozjs/src/lib.rs:pub const JS_DEFAULT_ZEAL_FREQ: u32 = 100;
rust-mozjs/src/jsapi_windows_gcc_64.rs:    #[link_name = "_Z12JS_GetGCZealP9JSContextPhPjS2_"]
rust-mozjs/src/jsapi_windows_gcc_64.rs:    pub fn JS_GetGCZeal(cx: *mut JSContext, zeal: *mut u8,
rust-mozjs/src/jsapi_windows_gcc_64.rs:    #[link_name = "_Z12JS_SetGCZealP9JSContexthj"]
rust-mozjs/src/jsapi_windows_gcc_64.rs:    pub fn JS_SetGCZeal(cx: *mut JSContext, zeal: u8, frequency: u32);
rust-mozjs/src/jsapi_linux_64.rs:    #[link_name = "_Z12JS_GetGCZealP9JSContextPhPjS2_"]
rust-mozjs/src/jsapi_linux_64.rs:    pub fn JS_GetGCZeal(cx: *mut JSContext, zeal: *mut u8,
rust-mozjs/src/jsapi_linux_64.rs:    #[link_name = "_Z12JS_SetGCZealP9JSContexthj"]
rust-mozjs/src/jsapi_linux_64.rs:    pub fn JS_SetGCZeal(cx: *mut JSContext, zeal: u8, frequency: u32);

Should I just put #[cfg(debugmozjs)] in front of each declaration?

**Comment by michaelwu** [comment]
According to https://github.com/servo/mozjs/blob/master/mozjs/js/src/jsapi.h#L4809 there's one function you're missing.

Don't make it conditional. Just delete it. The bindings generator can't generate conditional things so it's not worth it.

**Comment by asajeffrey** [comment]
OK, I removed them from the generated rust-mozjs/src/jsapi_ARCH.rs files, it works locally (where ARCH is linux_64). Are these files regenerated from mozjs/mozjs/js/src/jsapi.h? If so, should the zeal functions also be removed from jsapi.h, jsapi.hpp and jsapi.cpp?

**Comment by michaelwu** [comment]
No, don't modify the c++ files. The functions are already removed when gc zeal isn't enabled. If they weren't removed then we wouldn't have to remove them from the bindings.

**Comment by asajeffrey** [comment]
Will do. Of course, this is over in another repo, so I'll submit another PR.

**Comment by asajeffrey** [comment]
@michaelwu: I submitted a PR removing the gczeal bindings https://github.com/servo/rust-mozjs/pull/212

**Comment by asajeffrey** [comment]
@michaelwu: Thanks!

**Pull request merged**
