### PR TITLE
Match folder names to crate names

### LINKED ISSUE #411: Match folder names to crate names.
Currently we have `rust-mozjs` with `mozjs` crate and `mozjs` folder with `mozjs-sys` crate.

### PR DESCRIPTION
**Pull request by sagudev**
`mozjs` -> `mozjs-sys`
`rust-mozjs` -> `mozjs`

Fixes #411

### CODE REVIEW

**Comment by mrobinson** [comment]
I'm really happy to see this change. Looks like CI is failing.

**Comment by sagudev** [comment]
Ah, I will investigate tomorrow.

**Comment by sagudev** [comment]
Apparently `git mv` exists for a reason. Anyway it would be nice to merge this without squash again, as there is one big commit that does moving and one commit that fixes all scripts/docs about folder layout assumptions.

**Comment by mrobinson** [comment]
> Apparently `git mv` exists for a reason. Anyway it would be nice to merge this without squash again, as there is one big commit that does moving and one commit that fixes all scripts/docs about folder layout assumptions.

One benefit of squash here is that it allows git bisect to work.

**Comment by sagudev** [comment]
> > Apparently `git mv` exists for a reason. Anyway it would be nice to merge this without squash again, as there is one big commit that does moving and one commit that fixes all scripts/docs about folder layout assumptions.
> 
> One benefit of squash here is that it allows git bisect to work.

That's why rustc is doing bisects on merge commits. I wonder if `git bisect` can do it too.

**Comment by mrobinson** [comment]
> That's why rustc is doing bisects on merge commits. I wonder if `git bisect` can do it too.

Since the commit history of mozjs is now linear, there are no more merge commits even without squashing.

**Comment by mrobinson** [comment]
Perhaps a clearer way of stating this is mozjs-sys is "SpiderMonkey and low-level Rust bindings to its C++ API" Does that read a bit more clearly?

**Review by mrobinson — APPROVED** [review]

**Pull request merged**
