### PR TITLE
Update README.md

### LINKED ISSUE #287: Dead Link in README.md
The link for Spidermonkey points to a non-existent MDN page. Would recommend/ propose to change the destination to [the current spidermonkey website <https://spidermonkey.dev/>](https://spidermonkey.dev/).

### PR DESCRIPTION
**Pull request by Chaostheorie**
Resolves #287

### CODE REVIEW

**Comment by KiChjang** [comment]
@bors-servo r+

Thanks!

**Comment by jdm** [comment]
Something's wrong with the treeherder api at https://treeherder.mozilla.org/api/jobs/?push_id=894642 and giving me a bad gateway. We can retry tomorrow.

**Comment by jdm** [comment]
https://github.com/servo/mozjs/blob/ef986b1a2c23081fe4d37aeaab5323d3dec033f3/etc/get_mozjs.sh#L7 is failing to retrieve the expected data.

**Comment by Chaostheorie** [comment]
@jdm I'm interested why the pipeline test all builds for the rust code when it isn't modified. Won't this waste a lot of CI minutes over time?

Besides that, I think the issue stopping the tests is not related to this PR and I was wondering if it could jsut be merged,

**Comment by Chaostheorie** [comment]
@jdm Thank you for your help.

**Pull request merged**
