### PR TITLE
Update SpiderMonkey to ESR115.9

### PR DESCRIPTION
**Pull request by sagudev**
This should fix integrity check.

### CODE REVIEW

**Comment by wusyong** [comment]
I'll take some time to test the release and build script workflow tomorrow to see if that's fine in my fork.

**Review by jdm — APPROVED** [review]
Looks good!

**Comment by sagudev** [comment]
> I'll take some time to test the release and build script workflow tomorrow to see if that's fine in my fork.

This refers to #450, right?

**Comment by wusyong** [comment]
> This refers to #450, right?

Yeah I was thinking about testing autodownload with my fork [release](https://github.com/wusyong/mozjs/releases/tag/mozjs-sys-v0.115.9-0). It seems working with `MOZJS_ARCHIVE` and auto-download from build script itself. 👍

**Review by wusyong — APPROVED** [review]

**Pull request merged**
