### PR TITLE
Upgrade to SM 107.

### PR DESCRIPTION
**Pull request by jdm**
Building on https://github.com/servo/mozjs/pull/295/.

Known issues:
* [x] FromPropertyDescriptor and JS_GetPropertyDescriptor have been removed; /property_descriptor.rs needs to be updated

### CODE REVIEW

**Comment by Redfire75369** [comment]
I think some glue could be added to adapt the functions using `mozilla::Maybe` to functions just taking pointers. 
<https://searchfox.org/mozilla-central/source/mfbt/Maybe.h#349>

**Comment by sagudev** [comment]
The best option would be to glue mozilla::Maybe` to `Option`.

**Comment by Redfire75369** [comment]
Rust doesn't have a stable ABI so you can't do that. You can't guarantee the bit repesentation is the same.

**Comment by sagudev** [comment]
As for the CI failure, `update.py` scripts expects to be run from `.` not from `./mozjs`, but `get_mozjs*.sh` expects to be run from `./mozjs`. Maybe changing all of them to be run from `.` would be the most convenient  solution.

**Comment by jdm** [comment]
Once the UWP issues from #29079 are addressed we're ready to rebase and merge!

**Comment by sagudev** [comment]
Is there for every auto merge two CI runs? 
slika

**Comment by jdm** [comment]
Yeah, homu force pushes twice for some reason.

**Pull request merged**
