### PR TITLE
Set MAKEFLAGS to CARGO_MAKEFLAGS for the make command

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/mozjs/123)

### CODE REVIEW

**Comment by Eijebong** [comment]
Failure seems unrelated. Looks like some new warning about unused macros isn't happy

**Comment by nox** [comment]
```
make: *** internal error: invalid --jobserver-auth string '__rust_jobserver_semaphore_2744356833'.  Stop.
```

**Pull request merged**
