### PR TITLE
Revert "Copy all the sources to OUT_DIR before building them"

### LINKED ISSUE #218: Windows build fails during source file copying phase
I get a panic in https://github.com/servo/mozjs/blob/618398c43fe9ec2a471687a243808a399f077d2a/build.rs#L407 after modifying makefile.cargo and rebuilding.

### PR DESCRIPTION
**Pull request by jdm**
This reverts commit 1d588b233b4b0fc15b1ef4e0b7296f997bb7c748 and fixes #218.

### CODE REVIEW

**Comment by nox** [comment]
Is this really important to land? It's included in my smup without losing the things that we should keep from this commit.

**Comment by jdm** [comment]
It prevents 332d090f455c40a583c62c82289f2b24b7c0d4cc and https://github.com/servo/mozjs/pull/219 from being used by Servo master right now. I would prefer not to leave this repository in its unusable state longer than necessary.

**Comment by nox** [comment]
Superseded by #227.

**Pull request closed without merging**
