### PR TITLE
Update to SpiderMonkey 87

### PR DESCRIPTION
**Pull request by sagudev**
Yes, you readied correctly. Mozilla creates mozjs tar one week prior release.

### CODE REVIEW

**Comment by sagudev** [comment]
@jdm?

**Comment by jdm** [comment]
This is good to merge if the tests in https://github.com/servo/servo/pull/28300 pass.

**Comment by sagudev** [comment]
Tests passed

**Comment by sagudev** [comment]
That took long.

**Comment by sagudev** [comment]
> 
> 
> That took long. GitHub queue was long.

And that got me thinking, should build matrix be reduced. For merged PR there are currently 3*matrix builds:

1. on PR build
2. @bors-servo build (push event)
3. master (push event)

And I think we can remove last point, as bors build is made against master branch.

**Comment by jdm** [comment]
Yes,  that makes sense to me.

**Pull request merged**
